name: CI
on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.10.3'
    - uses: actions/cache@v1
      with:
        path: ~/.stack
        key: "${{ runner.os }}-v3-${{ hashFiles('goldplate.cabal', 'stack.yaml', 'stack.yaml.lock') }}"
    - name: Build
      run: |
        stack build --system-ghc
    - name: Test
      run: |
        stack exec --system-ghc -- goldplate --pretty-diff tests/
